In [2]:
import os 
import glob
import pandas as pd 
os.chdir('/mnt/BioHome/jreyna/jreyna/projects/dchallenge/')

## Load Coloc SNP data

In [63]:
globs = 'results/main/coloc/Results/eQTL_Catalogue/*/*/*/FINAL_Summary_Coloc_Gene_SNP_Pairs.bed'
globs = glob.glob(globs)

coloc_data = []
for fn in globs:
    
    file_info = fn.split('/')    
    gwas_source = file_info[5]
    eqtl_source = file_info[6]
    ge_source = file_info[7]
    
    num_lines = len(open(fn).readlines())
    if num_lines > 0: 
        
        #print(fn)
        
        tdf = pd.read_table(fn)
        tdf.loc[:, 'gwas_source'] = gwas_source
        tdf.loc[:, 'eqtl_source'] = eqtl_source
        tdf.loc[:, 'ge_source'] = ge_source
    
        coloc_data.append(tdf)

In [64]:
coloc_data = pd.concat(coloc_data)

In [65]:
coloc_summary = coloc_data.groupby(['gwas_source', 'eqtl_source', 'ge_source'])#.pos.count()
coloc_summary = coloc_summary.pos.count().to_frame()
coloc_summary.columns = ['Number of SNPs in Coloc']
coloc_summary

                                                                     Number of SNPs in Coloc
gwas_source               eqtl_source      ge_source
T1D_25751624              BLUEPRINT        T-cell                                          1
                                           monocyte                                        1
                                           neutrophil                                      1
                          GENCORD          LCL                                             2
                                           T-cell                                          2
                          GTEx             LCL                                             3
                                           blood                                           1
                          Lepik_2017       blood                                           1
                          Quach_2016       monocyte_IAV                                    2
                                           monocyte_LPS                                    1
                                           monocyte_Pam3CSK4                               1
                                           monocyte_R848                                   2
                                           monocyte_naive                                  2
                          Schmiedel_2018   B-cell_naive                                    2
                                           CD4_T-cell_anti-CD3-CD28                        2
                                           CD4_T-cell_naive                                2
                                           CD8_T-cell_anti-CD3-CD28                        4
                                           NK-cell_naive                                   3
                                           Tfh_memory                                      4
                                           Th1-17_memory                                   2
                                           Th17_memory                                     2
                                           Th1_memory                                      1
                                           Th2_memory                                      2
                                           Treg_memory                                     1
                                           Treg_naive                                      1
                                           monocyte_CD16_naive                             1
                                           monocyte_naive                                  1
                          van_de_Bunt_2015 pancreatic_islet                                1
T1D_32005708              BLUEPRINT        monocyte                                        1
                                           neutrophil                                      1
...                                                                                      ...
T1D_34012112_Gaulton      GTEx             LCL                                             5
                          Quach_2016       monocyte_IAV                                    3
                                           monocyte_Pam3CSK4                               1
                                           monocyte_R848                                   3
                          Schmiedel_2018   B-cell_naive                                    1
                                           CD4_T-cell_anti-CD3-CD28                        3
                                           CD4_T-cell_naive                                1
                                           CD8_T-cell_naive                                1
                                           NK-cell_naive                                   1
                                           Tfh_memory                                      2
                                           Th1-17_memory                                   2
                                           Th17_memory                                     3
                                           Th1_memory                                      4
                                           Th2_memory                                      4
                                           Treg_memory                                     2
                                           Treg_naive                                      5
                                           test                                            1
                          van_de_Bunt_2015 pancreatic_islet                                1
T1D_34594039_GCST90018925 BLUEPRINT        T-cell                                          1
                                           monocyte                                        1
                          GENCORD          T-cell                                          1
                          GTEx             LCL                                             1
                                           pancreas                                        1
                          Schmiedel_2018   CD8_T-cell_anti-CD3-CD28                        1
                                           NK-cell_naive                                   1
                                           Tfh_memory                                      2
                                           Th17_memory                                     1
                                           Th1_memory                                      1
                                           Th2_memory                                      1
                                           monocyte_CD16_naive                             1

[85 rows x 1 columns]

## Load LD data

In [67]:
globs = glob.glob('results/main/coloc/eQTL_Catalogue/*/*/*/*/ldpairs/coloc_ld_snps.txt')

ld_data = []
ld_summary_zeros = []
for fn in globs:
    
    file_info = fn.split('/')
    gwas_source = file_info[4]
    genome_ref = file_info[5]
    eqtl_source = file_info[6]
    ge_source = file_info[7]
    
    num_lines = len(open(fn).readlines())
    if num_lines > 0: 
        
        #print(fn)

        tdf = pd.read_table(fn)
        tdf.loc[:, 'gwas_source'] = gwas_source
        tdf.loc[:, 'genome_ref'] = genome_ref
        tdf.loc[:, 'eqtl_source'] = eqtl_source
        tdf.loc[:, 'ge_source'] = ge_source
        tdf.drop_duplicates(subset=['rsID', 'ld_rsID'], inplace=True)
        ld_data.append(tdf)
        
    else:
        ld_summary_zeros.append([gwas_source, eqtl_source, ge_source, 0])

In [70]:
ld_df = pd.concat(ld_data)

In [71]:
ld_summary = ld_df.groupby(['gwas_source', 'eqtl_source', 'ge_source'])#.pos.count()
ld_summary = ld_summary.pos.count().to_frame()
ld_summary.columns = ['Number of SNPs in LD']

In [72]:
ld_summary_zeros = pd.DataFrame(ld_summary_zeros)
ld_summary_zeros.set_index([0,1,2], inplace=True)
ld_summary_zeros.columns = ['Number of SNPs in LD']

In [73]:
ld_summary = pd.concat([ld_summary, ld_summary_zeros])

In [74]:
ld_summary

                                                                     Number of SNPs in LD
gwas_source               eqtl_source      ge_source
T1D_25751624              Lepik_2017       blood                                       23
T1D_34012112_Gaulton      BLUEPRINT        monocyte                                     9
                                           neutrophil                                  13
                          Quach_2016       monocyte_IAV                                17
                                           monocyte_Pam3CSK4                           17
                                           monocyte_R848                               18
                          Schmiedel_2018   Th17_memory                                  9
                                           Treg_naive                                  42
                          BLUEPRINT        T-cell                                       0
                          Schmiedel_2018   CD4_T-cell_anti-CD3-CD28                     0
                                           Treg_memory                                  0
                                           NK-cell_naive                                0
                                           Th1_memory                                   0
                                           B-cell_naive                                 0
                                           Tfh_memory                                   0
                                           CD8_T-cell_naive                             0
                                           Th2_memory                                   0
                                           CD4_T-cell_naive                             0
                                           Th1-17_memory                                0
                          van_de_Bunt_2015 pancreatic_islet                             0
                          GTEx             LCL                                          0
T1D_34594039_GCST90018925 Schmiedel_2018   Th17_memory                                  0
                                           monocyte_CD16_naive                          0
                                           Tfh_memory                                   0
                                           Th1_memory                                   0
                                           NK-cell_naive                                0
                                           CD8_T-cell_anti-CD3-CD28                     0
                                           Th2_memory                                   0
                          BLUEPRINT        monocyte                                     0
                                           T-cell                                       0
...                                                                                   ...
T1D_32005708              GTEx             LCL                                          0
                          GENCORD          T-cell                                       0
                                           LCL                                          0
T1D_25751624              GTEx             LCL                                          0
                                           blood                                        0
                          Schmiedel_2018   CD4_T-cell_anti-CD3-CD28                     0
                                           NK-cell_naive                                0
                                           CD4_T-cell_naive                             0
                                           Th2_memory                                   0
                                           CD8_T-cell_anti-CD3-CD28                     0
                                           Th17_memory                                  0
                                           Th1_memory                                   0
                                           Treg_naive                                   0
                                           Tfh_memory                                   0
                                           Treg_memory                                  0
                                           Th1-17_memory                                0
                                           B-cell_naive                                 0
                                           monocyte_naive                               0
                                           monocyte_CD16_naive                          0
                          BLUEPRINT        T-cell                                       0
                                           neutrophil                                   0
                                           monocyte                                     0
                          van_de_Bunt_2015 pancreatic_islet                             0
                          GENCORD          T-cell                                       0
                                           LCL                                          0
                          Quach_2016       monocyte_naive                               0
                                           monocyte_LPS                                 0
                                           monocyte_IAV                                 0
                                           monocyte_Pam3CSK4                            0
                                           monocyte_R848                                0

[84 rows x 1 columns]

## Merge

In [76]:
pd.options.display.min_rows = 100

In [77]:
summary = pd.merge(coloc_summary, ld_summary, left_index=True, right_index=True, how='outer')

In [78]:
summary.sort_values('Number of SNPs in LD', ascending=False)

                                                                     Number of SNPs in Coloc  \
gwas_source               eqtl_source      ge_source
T1D_34012112_Gaulton      Schmiedel_2018   Treg_naive                                      5
T1D_25751624              Lepik_2017       blood                                           1
T1D_34012112_Gaulton      Quach_2016       monocyte_R848                                   3
                                           monocyte_Pam3CSK4                               1
                                           monocyte_IAV                                    3
                          BLUEPRINT        neutrophil                                      2
                                           monocyte                                        2
                          Schmiedel_2018   Th17_memory                                     3
                                           CD4_T-cell_anti-CD3-CD28                        3
                                           B-cell_naive                                    1
                          GTEx             LCL                                             5
T1D_25751624              BLUEPRINT        T-cell                                          1
T1D_34012112_Gaulton      Schmiedel_2018   CD8_T-cell_naive                                1
                          BLUEPRINT        T-cell                                          2
T1D_32005708              van_de_Bunt_2015 pancreatic_islet                                2
                          Schmiedel_2018   monocyte_naive                                  2
                                           monocyte_CD16_naive                             1
                                           Treg_naive                                      1
                                           Treg_memory                                     1
                                           Th2_memory                                      1
                                           Th1_memory                                      1
T1D_34012112_Gaulton      Schmiedel_2018   CD4_T-cell_naive                                1
                                           Tfh_memory                                      2
                                           NK-cell_naive                                   1
T1D_34594039_GCST90018925 GTEx             LCL                                             1
                          Schmiedel_2018   Th2_memory                                      1
                                           Th1_memory                                      1
                                           Th17_memory                                     1
                                           Tfh_memory                                      2
                                           NK-cell_naive                                   1
...                                                                                      ...
T1D_25751624              Quach_2016       monocyte_LPS                                    1
                                           monocyte_IAV                                    2
                          GTEx             blood                                           1
                                           LCL                                             3
                          GENCORD          T-cell                                          2
                                           LCL                                             2
                          BLUEPRINT        neutrophil                                      1
                          Schmiedel_2018   Th17_memory                                     2
                                           Th2_memory                                      2
T1D_32005708              Schmiedel_2018   NK-cell_naive                                   1
T1D_25751624              Schmiedel_2018   Treg_memory                                     1
T1D_32005708              Schmiedel_2018   CD8_T-cell_naive                                1
                                           CD8_T-cell_anti-CD3-CD28                        1
                                           CD4_T-cell_anti-CD3-CD28                        2
                                           B-cell_naive                                    2
                          Quach_2016       monocyte_IAV                                    1
                          Lepik_2017       blood                                           1
                          GTEx             pancreas                                        1
                                           blood                                           1
                                           LCL                                             1
                          GENCORD          T-cell                                          2
                                           LCL                                             2
                          BLUEPRINT        neutrophil                                      1
                                           monocyte                                        1
T1D_25751624              van_de_Bunt_2015 pancreatic_islet                                1
                          Schmiedel_2018   monocyte_naive                                  1
                                           monocyte_CD16_naive                             1
                                           Treg_naive                                      1
T1D_34594039_GCST90018925 Schmiedel_2018   monocyte_CD16_naive                             1
T1D_34012112_Gaulton      Schmiedel_2018   test                                            1

                                                                     Number of SNPs in LD
gwas_source               eqtl_source      ge_source
T1D_34012112_Gaulton      Schmiedel_2018   Treg_naive                                42.0
T1D_25751624              Lepik_2017       blood                                     23.0
T1D_34012112_Gaulton      Quach_2016       monocyte_R848                             18.0
                                           monocyte_Pam3CSK4                         17.0
                                           monocyte_IAV                              17.0
                          BLUEPRINT        neutrophil                                13.0
                                           monocyte                                   9.0
                          Schmiedel_2018   Th17_memory                                9.0
                                           CD4_T-cell_anti-CD3-CD28                   0.0
                                           B-cell_naive                               0.0
                          GTEx             LCL                                        0.0
T1D_25751624              BLUEPRINT        T-cell                                     0.0
T1D_34012112_Gaulton      Schmiedel_2018   CD8_T-cell_naive                           0.0
                          BLUEPRINT        T-cell                                     0.0
T1D_32005708              van_de_Bunt_2015 pancreatic_islet                           0.0
                          Schmiedel_2018   monocyte_naive                             0.0
                                           monocyte_CD16_naive                        0.0
                                           Treg_naive                                 0.0
                                           Treg_memory                                0.0
                                           Th2_memory                                 0.0
                                           Th1_memory                                 0.0
T1D_34012112_Gaulton      Schmiedel_2018   CD4_T-cell_naive                           0.0
                                           Tfh_memory                                 0.0
                                           NK-cell_naive                              0.0
T1D_34594039_GCST90018925 GTEx             LCL                                        0.0
                          Schmiedel_2018   Th2_memory                                 0.0
                                           Th1_memory                                 0.0
                                           Th17_memory                                0.0
                                           Tfh_memory                                 0.0
                                           NK-cell_naive                              0.0
...                                                                                   ...
T1D_25751624              Quach_2016       monocyte_LPS                               0.0
                                           monocyte_IAV                               0.0
                          GTEx             blood                                      0.0
                                           LCL                                        0.0
                          GENCORD          T-cell                                     0.0
                                           LCL                                        0.0
                          BLUEPRINT        neutrophil                                 0.0
                          Schmiedel_2018   Th17_memory                                0.0
                                           Th2_memory                                 0.0
T1D_32005708              Schmiedel_2018   NK-cell_naive                              0.0
T1D_25751624              Schmiedel_2018   Treg_memory                                0.0
T1D_32005708              Schmiedel_2018   CD8_T-cell_naive                           0.0
                                           CD8_T-cell_anti-CD3-CD28                   0.0
                                           CD4_T-cell_anti-CD3-CD28                   0.0
                                           B-cell_naive                               0.0
                          Quach_2016       monocyte_IAV                               0.0
                          Lepik_2017       blood                                      0.0
                          GTEx             pancreas                                   0.0
                                           blood                                      0.0
                                           LCL                                        0.0
                          GENCORD          T-cell                                     0.0
                                           LCL                                        0.0
                          BLUEPRINT        neutrophil                                 0.0
                                           monocyte                                   0.0
T1D_25751624              van_de_Bunt_2015 pancreatic_islet                           0.0
                          Schmiedel_2018   monocyte_naive                             0.0
                                           monocyte_CD16_naive                        0.0
                                           Treg_naive                                 0.0
T1D_34594039_GCST90018925 Schmiedel_2018   monocyte_CD16_naive                        0.0
T1D_34012112_Gaulton      Schmiedel_2018   test                                       NaN

[85 rows x 2 columns]

## Checking Sample 'T1D_25751624', 'Lepik_2017', 'blood'

In [80]:
ld_summary.loc[['T1D_25751624']]

                                                        Number of SNPs in LD
gwas_source  eqtl_source      ge_source
T1D_25751624 Lepik_2017       blood                                       23
             GTEx             LCL                                          0
                              blood                                        0
             Schmiedel_2018   CD4_T-cell_anti-CD3-CD28                     0
                              NK-cell_naive                                0
                              CD4_T-cell_naive                             0
                              Th2_memory                                   0
                              CD8_T-cell_anti-CD3-CD28                     0
                              Th17_memory                                  0
                              Th1_memory                                   0
                              Treg_naive                                   0
                              Tfh_memory                                   0
                              Treg_memory                                  0
                              Th1-17_memory                                0
                              B-cell_naive                                 0
                              monocyte_naive                               0
                              monocyte_CD16_naive                          0
             BLUEPRINT        T-cell                                       0
                              neutrophil                                   0
                              monocyte                                     0
             van_de_Bunt_2015 pancreatic_islet                             0
             GENCORD          T-cell                                       0
                              LCL                                          0
             Quach_2016       monocyte_naive                               0
                              monocyte_LPS                                 0
                              monocyte_IAV                                 0
                              monocyte_Pam3CSK4                            0
                              monocyte_R848                                0

In [81]:
check =  ld_df[(ld_df['gwas_source'] == 'T1D_25751624') &
        (ld_df['eqtl_source'] == 'Lepik_2017') &
        (ld_df['ge_source'] == 'blood')]

In [82]:
check['ld_rsID'].nunique()

23

In [83]:
check[['rsID', 'ld_rsID']].sort_values(['rsID', 'ld_rsID'])

           rsID      ld_rsID
0   rs572801429  rs187909913
1   rs572801429  rs188028689
2   rs572801429  rs529219743
3   rs572801429  rs529230843
4   rs572801429  rs529915872
5   rs572801429  rs532937186
6   rs572801429  rs538842367
7   rs572801429  rs539342013
8   rs572801429  rs541382506
9   rs572801429  rs543249929
10  rs572801429  rs546384598
11  rs572801429  rs546447704
12  rs572801429  rs551091348
13  rs572801429  rs556514745
14  rs572801429  rs558302740
15  rs572801429  rs558472526
16  rs572801429  rs559377566
17  rs572801429  rs562476051
18  rs572801429  rs565284389
19  rs572801429  rs571024368
20  rs572801429  rs572466125
21  rs572801429  rs572801429
22  rs572801429   rs74336270

In [84]:
check.value_counts('ld_rsID')

ld_rsID
rs187909913    1
rs551091348    1
rs572801429    1
rs572466125    1
rs571024368    1
rs565284389    1
rs562476051    1
rs559377566    1
rs558472526    1
rs558302740    1
rs556514745    1
rs546447704    1
rs188028689    1
rs546384598    1
rs543249929    1
rs541382506    1
rs539342013    1
rs538842367    1
rs532937186    1
rs529915872    1
rs529230843    1
rs529219743    1
rs74336270     1
dtype: int64