In [1]:
######## snakemake preamble start (automatically inserted, do not edit) ########
import sys; sys.path.extend(['/mnt/BioAdHoc/Groups/vd-ay/jreyna/software/mambaforge/envs/hichip-db/lib/python3.9/site-packages', '/mnt/BioAdHoc/Groups/vd-ay/jreyna/projects/dchallenge/workflow/rules/../scripts/sgls']); import pickle; snakemake = pickle.loads(b'\x80\x04\x95>\x0f\x00\x00\x00\x00\x00\x00\x8c\x10snakemake.script\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94\x8c\x0csnakemake.io\x94\x8c\nInputFiles\x94\x93\x94)\x81\x94(\x8c[results/main/sgls/T1D_34012112_Gaulton/Quach_2016/monocyte_R848/eqtls.coloc_filtered.tsv.gz\x94\x8cWresults/main/coloc/Results/eQTL_Catalogue/T1D_34012112_Gaulton/Quach_2016/monocyte_R848\x94\x8cpresults/main/coloc/eQTL_Catalogue/T1D_34012112_Gaulton/GRCh37/Quach_2016/monocyte_R848/ldpairs/coloc_ld_snps.txt\x94\x8ceresults/main/h3k27ac_hichip/monocyte_naive/FitHiChIP_S/FitHiChIP.interactions_FitHiC_Q0.01.grch38.bed\x94\x8c"results/refs/hg38/hg38.chrom.sizes\x94\x8c3results/refs/gencode/v30/gencode.v30.annotation.bed\x94e}\x94(\x8c\x06_names\x94}\x94(\x8c\x04eqtl\x94K\x00K\x01\x86\x94\x8c\tcoloc_dir\x94K\x01N\x86\x94\x8c\x05coloc\x94K\x02N\x86\x94\x8c\x05loops\x94K\x03N\x86\x94\x8c\x0cgenome_sizes\x94K\x04N\x86\x94\x8c\x07gencode\x94K\x05N\x86\x94u\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh!\x8c\tfunctools\x94\x8c\x07partial\x94\x93\x94h\x06\x8c\x19Namedlist._used_attribute\x94\x93\x94\x85\x94R\x94(h\')}\x94\x8c\x05_name\x94h!sNt\x94bh"h%h\'\x85\x94R\x94(h\')}\x94h+h"sNt\x94bh\x13h\x06\x8c\tNamedlist\x94\x93\x94)\x81\x94h\na}\x94(h\x11}\x94h\x1f]\x94(h!h"eh!h%h\'\x85\x94R\x94(h\')}\x94h+h!sNt\x94bh"h%h\'\x85\x94R\x94(h\')}\x94h+h"sNt\x94bubh\x15h\x0bh\x17h\x0ch\x19h\rh\x1bh\x0eh\x1dh\x0fub\x8c\x06output\x94h\x06\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94\x8c]results/main/sgls/ldpairs/T1D_34012112_Gaulton/GRCh37/Quach_2016/monocyte_R848/monocyte_naive\x94a}\x94(h\x11}\x94\x8c\x06outdir\x94K\x00N\x86\x94sh\x1f]\x94(h!h"eh!h%h\'\x85\x94R\x94(h\')}\x94h+h!sNt\x94bh"h%h\'\x85\x94R\x94(h\')}\x94h+h"sNt\x94bhFhCub\x8c\x06params\x94h\x06\x8c\x06Params\x94\x93\x94)\x81\x94M\xa8aa}\x94(h\x11}\x94\x8c\tloop_slop\x94K\x00N\x86\x94sh\x1f]\x94(h!h"eh!h%h\'\x85\x94R\x94(h\')}\x94h+h!sNt\x94bh"h%h\'\x85\x94R\x94(h\')}\x94h+h"sNt\x94bhWM\xa8aub\x8c\twildcards\x94h\x06\x8c\tWildcards\x94\x93\x94)\x81\x94(\x8c\x14T1D_34012112_Gaulton\x94\x8c\x06GRCh37\x94\x8c\nQuach_2016\x94\x8c\rmonocyte_R848\x94\x8c\x0emonocyte_naive\x94e}\x94(h\x11}\x94(\x8c\x0bgwas_source\x94K\x00N\x86\x94\x8c\nref_genome\x94K\x01N\x86\x94\x8c\x0beqtl_source\x94K\x02N\x86\x94\x8c\tge_source\x94K\x03N\x86\x94\x8c\x0bloop_source\x94K\x04N\x86\x94uh\x1f]\x94(h!h"eh!h%h\'\x85\x94R\x94(h\')}\x94h+h!sNt\x94bh"h%h\'\x85\x94R\x94(h\')}\x94h+h"sNt\x94bhmhfhohghqhhhshihuhjub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x06\x8c\tResources\x94\x93\x94)\x81\x94(K\x01K\x01\x8c\x08/scratch\x94M\xc0]K\x01K\x01e}\x94(h\x11}\x94(\x8c\x06_cores\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06tmpdir\x94K\x02N\x86\x94\x8c\x06mem_mb\x94K\x03N\x86\x94\x8c\x05nodes\x94K\x04N\x86\x94\x8c\x03ppn\x94K\x05N\x86\x94uh\x1f]\x94(h!h"eh!h%h\'\x85\x94R\x94(h\')}\x94h+h!sNt\x94bh"h%h\'\x85\x94R\x94(h\')}\x94h+h"sNt\x94bh\x88K\x01h\x8aK\x01h\x8ch\x85h\x8eM\xc0]h\x90K\x01h\x92K\x01ub\x8c\x03log\x94h\x06\x8c\x03Log\x94\x93\x94)\x81\x94\x8cnresults/main/sgls/logs/annotate_colocs.T1D_34012112_Gaulton.GRCh37.Quach_2016.monocyte_R848.monocyte_naive.log\x94a}\x94(h\x11}\x94h\x1f]\x94(h!h"eh!h%h\'\x85\x94R\x94(h\')}\x94h+h!sNt\x94bh"h%h\'\x85\x94R\x94(h\')}\x94h+h"sNt\x94bub\x8c\x06config\x94}\x94(\x8c\x0chichip_db_py\x94\x8c;/mnt/BioHome/jreyna/software/anaconda3/hichip-db/bin/python\x94\x8c\nhic_tls_py\x94\x8c>/mnt/BioHome/jreyna/software/anaconda3/envs/hic_tls/bin/python\x94\x8c\thic_tls_R\x94\x8c\'/share/apps/R/3.4.3/lib64/R/bin/Rscript\x94\x8c\x02R4\x94\x8c2/mnt/BioHome/jreyna/R-Versions/R-4.0.3/bin/Rscript\x94\x8c\x06fithic\x94\x8c4/mnt/BioHome/jreyna/software/fithic/fithic/fithic.py\x94\x8c\nfithic_tls\x94\x8c8/mnt/BioHome/jreyna/software/fithic/fithic/fithic_tls.py\x94\x8c\rhicpro2fithic\x94\x8cA/mnt/BioHome/jreyna/software/fithic/fithic/utils/HiCPro2FitHiC.py\x94\x8c\x0chicpro_utils\x94\x8c//mnt/BioHome/jreyna/software/HiC-Pro/bin/utils/\x94\x8c\x0cjuicer_tools\x94\x8c{/mnt/BioAdHoc/Groups/vd-ay/abhijit/overflow/proj_overflow/Alternate_Chromosomal_structures/juicer_tools.1.8.9_jcuda.0.8.jar\x94\x8c\x05Rpath\x94\x8c!/share/apps/R/3.4.3/lib64/R/bin/R\x94\x8c\x06CLINES\x94]\x94(\x8c\x04A549\x94\x8c\x05Caki2\x94\x8c\x06HEK293\x94\x8c\x05LNCaP\x94\x8c\x08NCI-H460\x94\x8c\x05Panc1\x94\x8c\x05SKNSH\x94e\x8c\x12DIXON_HIC_OVERLAPS\x94]\x94(\x8c\x04A549\x94\x8c\x05Caki2\x94\x8c\x05LNCaP\x94\x8c\x08NCI-H460\x94\x8c\x05Panc1\x94\x8c\x05SKNSH\x94e\x8c\x12DIXON_WGS_OVERLAPS\x94]\x94(\x8c\x04A549\x94\x8c\x05Caki2\x94\x8c\x05LNCaP\x94\x8c\x08NCI-H460\x94\x8c\x05Panc1\x94e\x8c\x08hictrans\x94\x8c,/home/jreyna/software/HiCtrans/hictrans.v3.R\x94\x8c\x05hicnv\x94\x8c&/home/jreyna/software/HiCnv/hicnv_v2.R\x94\x8c\rhicnv_scripts\x94\x8c$/home/jreyna/software/HiCnv/scripts/\x94\x8c\x07python2\x94\x8cD/mnt/BioHome/jreyna/software/anaconda3/envs/python_2.7.18/bin/python\x94\x8c\x08mustache\x94\x8cA/mnt/BioHome/jreyna/software/anaconda3/envs/mustache/bin/mustache\x94\x8c\x0fmustache_python\x94\x8c?/mnt/BioHome/jreyna/software/anaconda3/envs/mustache/bin/python\x94\x8c\x14juicer_tools_1.13.02\x94\x8c./home/jreyna/software/juicer_tools_1.13.02.jar\x94\x8c\x06cooler\x94\x8c>/mnt/BioHome/jreyna/software/anaconda3/envs/hic_tls/bin/cooler\x94\x8c\x05bgzip\x94\x8c=/mnt/BioHome/jreyna/software/anaconda3/envs/hic_tls/bin/bgzip\x94\x8c\x08liftover\x94\x8c1/home/jreyna/software/UCSC_Browser_Tools/liftOver\x94\x8c\x10hichip_db_python\x94\x8c4/home/jreyna/software/anaconda3/hichip-db/bin/python\x94u\x8c\x04rule\x94\x8c\x19Find_SGS_for_Coloc_and_LD\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8cT/mnt/BioAdHoc/Groups/vd-ay/jreyna/projects/dchallenge/workflow/rules/../scripts/sgls\x94ub.'); from snakemake.logging import logger; logger.printshellcmds = False; import os; os.chdir(r'/mnt/BioAdHoc/Groups/vd-ay/jreyna/projects/dchallenge');
######## snakemake preamble end #########

import os 
import sys
import pybedtools as pbt
import pandas as pd
import numpy as np
import subprocess as sp
import json
from biolib import liftover as liftover_utility
from biolib import coordinates as biocoords
pbt.helpers.set_tempdir('/mnt/BioHome/jreyna/tmp/')
pbt.set_bedtools_path('/mnt/BioApps/bedtools/bin/')
bgzip = '/mnt/BioApps/tabix/tabix-0.2.6/bgzip'
tabix = '/mnt/BioApps/tabix/tabix-0.2.6/tabix'
res = 5000
pd.options.display.max_columns = 100

In [2]:
bedpe_6cols = ['chrA', 'startA', 'endA', 'chrB', 'startB', 'endB']
bedpe_10cols = ['chrA', 'startA', 'endA', 'chrB', 'startB', 'endB', 'name', 'score', 'strand1', 'strand2']

# Parse the Snakemake arguments

In [3]:
# snakemake.input = ['results/main/GRCh37/sgls/T1D_34012112_Gaulton/Quach_2016/monocyte_R848/eqtls.coloc_filtered.tsv.gz',
#               'results/main/coloc/eQTL_Catalogue/T1D_34012112_Gaulton/GRCh37/Quach_2016/monocyte_R848/',
#               'results/main/GRCh37/coloc/eQTL_Catalogue/T1D_34012112_Gaulton/Quach_2016/monocyte_R848/ldpairs/coloc_ld_snps.txt',
#               'results/main/h3k27ac_hichip/monocyte_naive/FitHiChIP_S/FitHiChIP.interactions_FitHiC_Q0.01.bed',
#               'results/refs/hg19/hg19.chrom.sizes',
#               'results/refs/gencode/v30/gencode.v30.annotation.grch37.bed']

In [4]:
eqtl_fn = snakemake.input[0]
coloc_fn = snakemake.input[2]
loop_fn = snakemake.input[3]
celltype = snakemake.wildcards[3]
gs_fn = snakemake.input[4]
genes_fn = snakemake.input[5]
loop_slop = snakemake.params[0]
outdir = snakemake.output[0]

In [5]:
snakemake.wildcards

['T1D_34012112_Gaulton',
 'GRCh37',
 'Quach_2016',
 'monocyte_R848',
 'monocyte_naive']

In [6]:
eqtl_fn

'results/main/sgls/T1D_34012112_Gaulton/Quach_2016/monocyte_R848/eqtls.coloc_filtered.tsv.gz'

In [7]:
coloc_fn

'results/main/coloc/eQTL_Catalogue/T1D_34012112_Gaulton/GRCh37/Quach_2016/monocyte_R848/ldpairs/coloc_ld_snps.txt'

In [8]:
loop_fn

'results/main/h3k27ac_hichip/monocyte_naive/FitHiChIP_S/FitHiChIP.interactions_FitHiC_Q0.01.grch38.bed'

In [9]:
gs_fn

'results/refs/hg38/hg38.chrom.sizes'

In [10]:
genes_fn

'results/refs/gencode/v30/gencode.v30.annotation.bed'

In [11]:
loop_slop

25000

In [12]:
outdir

'results/main/sgls/ldpairs/T1D_34012112_Gaulton/GRCh37/Quach_2016/monocyte_R848/monocyte_naive'

# Load the colocalization data

In [13]:
# load the colocalization data
coloc = pd.read_table(coloc_fn)

# rename the columns
rename_coloc_cols = {
    'chr': 'coloc_chr',
    'pos': 'coloc_pos',
    'pp_H0_Coloc_Summary': 'ppH0',
    'pp_H1_Coloc_Summary': 'ppH1',
    'pp_H2_Coloc_Summary': 'ppH2',
    'pp_H3_Coloc_Summary': 'ppH3',
    'pp_H4_Coloc_Summary': 'ppH4',
    'rs_id': 'coloc_rsid',
    'variant_id': 'varid',
    'geneName': 'geneid',
    'dist': 'dist',
    'pvalue': 'eqtl_pval',
    'FDR': 'eqtl_fdr',
    'slope_snp': 'eqtl_slope',
    'ref': 'ref',
    'alt': 'alt',
    'AC': 'AC',
    'AF': 'AF',
    'AN': 'AN',
    'slope_se_snp': 'eqtl_slope_se',
    'slope_gwas': 'gwas_slope',
    'slope_se_gwas': 'gwas_slope_se',
    'pval_nominal': 'gwas_pval',
    'SampleSize': 'sample_size',
    'rsID': 'coloc_rsid_dup',
    'ld_chr': 'chr',
    'ld_pos': 'pos',
    'ld_rsID': 'rsid'}
coloc.rename(columns=rename_coloc_cols, inplace=True)

# reorder the columns 
major_cols = ['chr', 'pos', 'rsid',
             'ppH0', 'ppH1', 'ppH2', 'ppH3', 'ppH4',
             'varid', 'geneid', 'dist',
             'eqtl_pval', 'eqtl_fdr', 'eqtl_slope',
             'ref', 'alt', 'AC', 'AF', 'AN',
             'eqtl_slope_se', 'gwas_slope', 'gwas_slope_se', 'gwas_pval',
             'coloc_chr', 'coloc_pos', 'coloc_rsid', 'LD']
coloc = coloc[major_cols]

# construct the sid
coloc.loc[:, 'sid'] = coloc['chr'].str.replace('chr', '') + ':' + coloc['pos'].astype(str)

In [14]:
# extract the most significant according the H4 
coloc_sig_df = coloc.loc[~coloc.duplicated(subset=['chr', 'pos', 'geneid']),]
coloc_sig_df.head()

,chr,pos,rsid,ppH0,ppH1,ppH2,ppH3,ppH4,varid,geneid,dist,eqtl_pval,eqtl_fdr,eqtl_slope,ref,alt,AC,AF,AN,eqtl_slope_se,gwas_slope,gwas_slope_se,gwas_pval,coloc_chr,coloc_pos,coloc_rsid,LD,sid
0,chr9,4285986,rs10758591,0,0,0.000916,0.192281,0.806803,9:4282536:A:G,ENSG00000107249,65856,0.00644,0.336787,-0.407677,A,G,1754,0.35024,5008,0.005361,-0.121582,0.013995,3.710000e-18,chr9,4282536,rs4380994,0.984588,9:4285986
1,chr9,4289196,rs10814914,0,0,0.000916,0.192281,0.806803,9:4282536:A:G,ENSG00000107249,65856,0.00644,0.336787,-0.407677,A,G,1754,0.35024,5008,0.005361,-0.121582,0.013995,3.710000e-18,chr9,4282536,rs4380994,0.976890,9:4289196
2,chr9,4290544,rs10814915,0,0,0.000916,0.192281,0.806803,9:4282536:A:G,ENSG00000107249,65856,0.00644,0.336787,-0.407677,A,G,1754,0.35024,5008,0.005361,-0.121582,0.013995,3.710000e-18,chr9,4282536,rs4380994,0.854214,9:4290544
3,chr9,4293150,rs10814916,0,0,0.000916,0.192281,0.806803,9:4282536:A:G,ENSG00000107249,65856,0.00644,0.336787,-0.407677,A,G,1754,0.35024,5008,0.005361,-0.121582,0.013995,3.710000e-18,chr9,4282536,rs4380994,0.849530,9:4293150
4,chr9,4296430,rs10814917,0,0,0.000916,0.192281,0.806803,9:4282536:A:G,ENSG00000107249,65856,0.00644,0.336787,-0.407677,A,G,1754,0.35024,5008,0.005361,-0.121582,0.013995,3.710000e-18,chr9,4282536,rs4380994,0.942558,9:4296430

In [15]:
coloc_sig_df.shape

(18, 28)

In [16]:
# collect the chr and position of the main colocalized snps 
coloc_snps = coloc.loc[(coloc['chr'] == coloc['coloc_chr']) & (coloc['pos'] == coloc['coloc_pos'])] 
#coloc_snps = coloc_snps[['chr', 'pos']].values.tolist()
#coloc_snps = set([tuple(x) for x in coloc_snps])
coloc_snps = coloc_snps['sid'].unique()

In [17]:
# make a pybedtool object for intersections
coloc_sig_full = coloc_sig_df.copy(deep=True)

In [18]:
# get the bin start and end coordinates for each snp
coloc_bins = coloc_sig_full.pos.apply(biocoords.get_snp_bin, args=(res,))
coloc_starts, coloc_ends = list(zip(*coloc_bins.values))
coloc_sig_df.loc[:, 'start'] = coloc_starts
coloc_sig_df.loc[:, 'end'] = coloc_ends

In [19]:
coloc_sig_df = coloc_sig_df[['chr', 'start', 'end', 'sid', 'rsid', 'varid']]
coloc_sig_pbt = pbt.BedTool.from_dataframe(coloc_sig_df.iloc[:, 0:5]).sort()

print('There are {} colocalized/LD SNP-gene pairs'.format(coloc_sig_df.shape[0]))

There are 18 colocalized/LD SNP-gene pairs

# Load the gene data

In [20]:
print('# Load the gene data')

# load the gencode coords
cols = ['chrom', 'start', 'end', 'strand', 'type', 'geneid', 'genename']
gencode = pd.read_table(genes_fn, header=None, names=cols)

# extract just the genes
genes_df = gencode.loc[gencode.type.isin(['gene'])]
genes_df = genes_df.loc[~genes_df.duplicated(subset='geneid'), :]
genes_df.loc[:, 'chrom'] = genes_df['chrom'].astype(str)
genes_df = genes_df.iloc[:, [0,1,2,6,5,3]]

# create a copy of the original gene bed before coordinate shrinking
orig_genes_df = genes_df.copy()

# convert the start/end position into start/end for the TSS
# if the gene is + then the start is uses as the tss otherwise
# the end is used as the tss
genes_df.loc[(genes_df.strand == '+'), 'end'] = genes_df.loc[(genes_df.strand == '+'), 'start']
genes_df.loc[(genes_df.strand == '+'), 'start'] = genes_df.loc[(genes_df.strand == '+'), 'start'] - 1
genes_df.loc[(genes_df.strand == '-'), 'end'] = genes_df.loc[(genes_df.strand == '-'), 'end']
genes_df.loc[(genes_df.strand == '-'), 'start'] = genes_df.loc[(genes_df.strand == '-'), 'end'] - 1

# Load the gene data

In [21]:
# get the bin start and end 
genes_pbt_pre = genes_df.copy()
gene_bins = genes_pbt_pre.start.apply(biocoords.get_snp_bin, args=(res,))
gene_starts, gene_ends = list(zip(*gene_bins.values))
genes_pbt_pre.loc[:, 'start'] = gene_starts 
genes_pbt_pre.loc[:, 'end'] = gene_ends

In [22]:
# make a genes pbt for intersection
print("# make a genes pbt for intersection")
print(genes_df.head())
genes_pbt = pbt.BedTool.from_dataframe(genes_pbt_pre).sort()

print('\nThere are {} genes in this GTF-derived file.'.format(genes_df.shape[0]))

# make a genes pbt for intersection
   chrom  start    end     genename           geneid strand
0   chr1  11868  11869      DDX11L1  ENSG00000223972      +
12  chr1  29569  29570       WASH7P  ENSG00000227232      -
25  chr1  17435  17436    MIR6859-1  ENSG00000278267      -
28  chr1  29553  29554  MIR1302-2HG  ENSG00000243485      +
36  chr1  30365  30366    MIR1302-2  ENSG00000284332      +

There are 58825 genes in this GTF-derived file.

In [23]:
genes_pbt_pre

        chrom  start    end     genename           geneid strand
0        chr1  10000  15000      DDX11L1  ENSG00000223972      +
12       chr1  25000  30000       WASH7P  ENSG00000227232      -
25       chr1  15000  20000    MIR6859-1  ENSG00000278267      -
28       chr1  25000  30000  MIR1302-2HG  ENSG00000243485      +
36       chr1  30000  35000    MIR1302-2  ENSG00000284332      +
...       ...    ...    ...          ...              ...    ...
2774280  chrM  10000  15000       MT-ND6  ENSG00000198695      -
2774285  chrM  10000  15000        MT-TE  ENSG00000210194      -
2774288  chrM  10000  15000       MT-CYB  ENSG00000198727      +
2774293  chrM  15000  20000        MT-TT  ENSG00000210195      +
2774296  chrM  15000  20000        MT-TP  ENSG00000210196      -

[58825 rows x 6 columns]

# Find all genes +/- 500kb of a colocalized/LD SNP

In [24]:
print('# Find all genes +/- 500kb of a colocalized/LD SNP')

# Find all genes +/- 500kb of a colocalized/LD SNP

In [25]:
slop = 1000000
print("# Find all genes +/- {}kb".format(int(slop/1000)))

# get a list of gene names within +- 500kb of the SNPs
fivekb_genes = coloc_sig_pbt.slop(b=slop, g=gs_fn)
fivekb_genes = fivekb_genes.intersect(genes_pbt, wa=True, wb=True)
fivekb_genes = fivekb_genes.to_dataframe()

fivekb_genes = fivekb_genes.iloc[:, [0,1,2,5,6,7,3,4,8,9,10]]
fivekb_genes.columns = bedpe_6cols + ['sid', 'rsid', 'genename', 'geneid', 'strand2']
fivekb_genes['strand1'] = '+'
fivekb_genes['name'] = fivekb_genes['rsid'] + '_' + fivekb_genes['genename']
fivekb_genes['score'] = '.'

# extract only major columns
major_cols = bedpe_10cols + ['sid', 'genename', 'geneid']
fivekb_genes = fivekb_genes[major_cols]

# Find all genes +/- 1000kb

In [26]:
print('There are {} colocalized snp-gene pairs within +/- 1000kb.'.format(fivekb_genes.shape[0]))

There are 738 colocalized snp-gene pairs within +/- 1000kb.

# Find the closest gene

In [27]:
print('# Find the closest gene')
closest_gene = coloc_sig_pbt.closest(genes_pbt, d=True)
closest_gene = closest_gene.to_dataframe().iloc[:, [0,1,2,5,6,7,3,4,8,9,11]]
closest_gene.columns = bedpe_6cols + ['sid', 'rsid', 'genename', 'geneid', 'dist']
closest_gene.set_index(['sid', 'geneid'], inplace=True)

# Find the closest gene

# Load the H3K27ac HiChIP loops

In [28]:
print('# Load the H3K27ac HiChIP loops')

# Load the H3K27ac HiChIP loops

In [29]:
print('# Get the loops')

# load the loop data
loops = pd.read_table(loop_fn)
tmp_loops = loops[['chr1', 's1', 'e1', 'chr2', 's2', 'e2']]
tmp_loops.rename(columns={'p': 'score'}, inplace=True)
tmp_loops.loc[:, 'name'] = '.'
tmp_loops.loc[:, 'score'] = loops['p']
tmp_loops.loc[:, 'strand1'] = '.'
tmp_loops.loc[:, 'strand2'] = '.'
loops = pbt.BedTool.from_dataframe(tmp_loops)
print(tmp_loops.head())

# Get the loops

/mnt/BioHome/jreyna/tmp//ipykernel_122267/1175980432.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_loops.rename(columns={'p': 'score'}, inplace=True)
/mnt/BioHome/jreyna/tmp//ipykernel_122267/1175980432.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_loops.loc[:, 'name'] = '.'
/mnt/BioHome/jreyna/tmp//ipykernel_122267/1175980432.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_loops.loc[:, 'score'] = loops['p']
/mnt/BioHome/jreyna/tmp//ipykernel_122267/1175980432.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_loops.loc[:, 'strand1'] = '.'
/mnt/BioHome/jreyna/tmp//ipykernel_122267/1175980432.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_loops.loc[:, 'strand2'] = '.'

    chr1        s1        e1   chr2        s2        e2 name         score  \
0   chr1    999620   1004620   chr1   1019620   1024620    .  4.851310e-06
1   chr1   1778561   1783561   chr1   3793436   3798436    .  4.646481e-08
2   chr1  26278509  26283509   chr1  26318509  26323509    .  3.598136e-06
3  chr10  44934552  44939552  chr10  44954552  44959552    .  5.488571e-06
4  chr10  44944552  44949552  chr10  44959552  44964552    .  5.173212e-06

  strand1 strand2
0       .       .
1       .       .
2       .       .
3       .       .
4       .       .

# Find SG pairs overlapping loops (both anchors + single anchor)

In [30]:
#print('# Find SNP-Genes overlapping loops (both anchors + single anchor)')

### Find SNP-Gene overlapping a loop (both anchors)

In [31]:
print('### Find SNP-Gene overlapping a loop (both anchors)')

### Find SNP-Gene overlapping a loop (both anchors)

In [32]:
# re-arranging to fit bedpe format
fivekb_gloops = fivekb_genes.copy()

# loading into pbt
fivekb_gloops = pbt.BedTool.from_dataframe(fivekb_gloops)
fivekb_gloops = fivekb_gloops.pair_to_pair(loops, type='both', slop=loop_slop, **{'is':True})
fivekb_gloops = fivekb_gloops.to_dataframe(disable_auto_names=True, header=None)

In [33]:
fivekb_gloops

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
0,chr9,3280000,5285000,chr9,3525000,3530000,rs10974435_RFX3,.,+,-,9:4283682,RFX3,ENSG00000080298,chr9,3505000,3510000,chr9,3575000,3580000,.,3.041319e-06,.,.
1,chr9,3280000,5285000,chr9,3525000,3530000,rs10974435_RFX3,.,+,-,9:4283682,RFX3,ENSG00000080298,chr9,3525000,3530000,chr9,4290000,4295000,.,1.384373e-07,.,.
2,chr9,3280000,5285000,chr9,3525000,3530000,rs10974435_RFX3,.,+,-,9:4283682,RFX3,ENSG00000080298,chr9,3525000,3530000,chr9,4675000,4680000,.,8.708686e-08,.,.
3,chr9,3280000,5285000,chr9,3525000,3530000,rs10974435_RFX3,.,+,-,9:4283682,RFX3,ENSG00000080298,chr9,3525000,3530000,chr9,4680000,4685000,.,8.661853e-08,.,.
4,chr9,3280000,5285000,chr9,3525000,3530000,rs10974435_RFX3,.,+,-,9:4283682,RFX3,ENSG00000080298,chr9,3525000,3530000,chr9,4980000,4985000,.,6.738191e-08,.,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1363,chr9,3295000,5300000,chr9,4980000,4985000,rs10814917_JAK2,.,+,+,9:4296430,JAK2,ENSG00000096968,chr9,4775000,4780000,chr9,4985000,4990000,.,6.905469e-07,.,.
1364,chr9,3295000,5300000,chr9,4980000,4985000,rs10814917_JAK2,.,+,+,9:4296430,JAK2,ENSG00000096968,chr9,4790000,4795000,chr9,4980000,4985000,.,7.275040e-07,.,.
1365,chr9,3295000,5300000,chr9,4980000,4985000,rs10814917_JAK2,.,+,+,9:4296430,JAK2,ENSG00000096968,chr9,4795000,4800000,chr9,4985000,4990000,.,7.086575e-07,.,.
1366,chr9,3295000,5300000,chr9,4980000,4985000,rs10814917_JAK2,.,+,+,9:4296430,JAK2,ENSG00000096968,chr9,4795000,4800000,chr9,4980000,4985000,.,3.311919e-06,.,.
1367,chr9,3295000,5300000,chr9,4980000,4985000,rs10814917_JAK2,.,+,+,9:4296430,JAK2,ENSG00000096968,chr9,4935000,4940000,chr9,4985000,4990000,.,3.041319e-06,.,.

In [34]:
if len(fivekb_gloops) > 0:
    fivekb_gloops_set = fivekb_gloops.iloc[:, [10, 12]]
    fivekb_gloops_uniq = set([tuple(x) for x in fivekb_gloops_set.values.tolist()])
else:
    print('WARNING: Found no overlap between the genes and loops.')
    fivekb_gloops_uniq = set()

print('There are {} SNP-Gene pairs with a loop.'.format(len(fivekb_gloops_uniq)))

There are 252 SNP-Gene pairs with a loop.

### Find coloc-SNP overlapping an anchor

In [35]:
print('### Find coloc-SNP overlapping an anchor')

### Find coloc-SNP overlapping an anchor

In [36]:
colocSNP_anchors = loops.pairtobed(coloc_sig_pbt.slop(b=loop_slop, g=gs_fn), type='either')
colocSNP_anchors = colocSNP_anchors.to_dataframe(disable_auto_names=True, header=None)

In [37]:
if len(colocSNP_anchors) > 0:
    colocSNP_anchors_set = colocSNP_anchors.iloc[:, 13]
else:
    print('WARNING: Found no overlap between coloc SNPs and loop anchors.')
    colocSNP_anchors_set = set()

print('There are {} SNPs which overlap a loop anchor.'.format(len(colocSNP_anchors_set)))

There are 18 SNPs which overlap a loop anchor.

# Construct the master table

In [38]:
print('# Construct master table')

# begin making the master
master = fivekb_genes.copy()

print('Master is starting with {} snp-gene pairs.'.format(master.shape[0]))

# adding back the rsid
coord_to_rsid = coloc[['sid', 'rsid']].set_index(['sid']).squeeze().to_dict()
master.loc[:, 'rsid'] = master.sid.apply(lambda x: coord_to_rsid[x])

# Construct master table
Master is starting with 738 snp-gene pairs.

#### Add eqtl results

In [39]:
print("# #### Add eqtl results")

# get eQTL's
eqtls = pd.read_table(eqtl_fn, header=0)#, nrows=1000)
eqtls = eqtls.loc[eqtls.type == 'SNP']
eqtls.drop(['molecular_trait_object_id', 'molecular_trait_id', 'type'], axis=1, inplace=True)
eqtls_rename_cols = {'chromosome': 'chr',
    'position': 'pos',
    'ref': 'ref',
    'alt': 'alt',
    'variant': 'variant',
    'ma_samples': 'ma_samples',
    'maf': 'maf',
    'pvalue': 'eqtl_pval',
    'beta': 'eqtl_beta',
    'se': 'eqtl_slop_se',
    'ac': 'ac',
    'an': 'an',
    'r2': 'r2',
    'gene_id': 'geneid',
    'median_tpm': 'median_tpm',
    'rsid': 'rsid',
    'dist': 'dist',
    'fdr': 'eqtl_fdr'}
eqtls.rename(columns=eqtls_rename_cols, inplace=True)
#eqtls['pos'] = eqtls['pos'].astype(int)
eqtls['sid'] = eqtls['chr'].astype(str) + ':' + eqtls['pos'].astype(str).str.replace('.0', '')
eqtls['is_eqtl_pair'] = -1 # add column to filter on eqtl snp status
eqtls.loc[(eqtls['eqtl_fdr'] <= 0.05), 'is_eqtl_pair'] = 1
eqtls.loc[(eqtls['eqtl_fdr'] > 0.05), 'is_eqtl_pair'] = 0

# #### Add eqtl results

/mnt/BioHome/jreyna/tmp//ipykernel_122267/3796354937.py:27: FutureWarning: The default value of regex will change from True to False in a future version.
  eqtls['sid'] = eqtls['chr'].astype(str) + ':' + eqtls['pos'].astype(str).str.replace('.0', '')

In [40]:
print('There are {} eQTLs.'.format(eqtls.shape[0]))

# need to use outer or else you exclude some eQTL's
master = master.merge(eqtls, on=['sid', 'geneid'], how='left')

There are 866453 eQTLs.

In [41]:
# update eqtl snp status
master.loc[master.is_eqtl_pair.isna(), 'is_eqtl_pair' ] = 0 

master.loc[:, 'is_eqtl_pair'] = master.loc[:, 'is_eqtl_pair'].astype(int)

# add gene names to entries with a missing name (after adding eQTL info)
master.loc[master.genename.isna(), 'genename'] = master.loc[master.genename.isna(), 'geneid']

# add missing chrA, chrB, startA and endA data for the eQTL rows
master.loc[master.chrA.isna(), 'chrA'] = 'chr' + master.loc[master.chrA.isna(), 'sid'].str.replace(':[0-9]+', '')
master.loc[master.chrB.isna(), 'chrB'] = 'chr' + master.loc[master.chrB.isna(), 'sid'].str.replace(':[0-9]+', '')
master.loc[master.startA.isna(), 'startA'] = (master.loc[master.startA.isna(), 'sid'].str.replace('[0-9]+:', '')).astype(int)
master.loc[master.startA.isna(), 'startA'] -= 1     
master.loc[master.endA.isna(), 'endA'] = master.loc[master.endA.isna(), 'sid'].str.replace('[0-9]+:', '')

print('After outer merging with eqtls, master has {} snp-gene pairs.'.format(master.shape[0]))

After outer merging with eqtls, master has 738 snp-gene pairs.

/mnt/BioHome/jreyna/tmp//ipykernel_122267/3088769827.py:10: FutureWarning: The default value of regex will change from True to False in a future version.
  master.loc[master.chrA.isna(), 'chrA'] = 'chr' + master.loc[master.chrA.isna(), 'sid'].str.replace(':[0-9]+', '')
/mnt/BioHome/jreyna/tmp//ipykernel_122267/3088769827.py:11: FutureWarning: The default value of regex will change from True to False in a future version.
  master.loc[master.chrB.isna(), 'chrB'] = 'chr' + master.loc[master.chrB.isna(), 'sid'].str.replace(':[0-9]+', '')
/mnt/BioHome/jreyna/tmp//ipykernel_122267/3088769827.py:12: FutureWarning: The default value of regex will change from True to False in a future version.
  master.loc[master.startA.isna(), 'startA'] = (master.loc[master.startA.isna(), 'sid'].str.replace('[0-9]+:', '')).astype(int)
/mnt/BioHome/jreyna/tmp//ipykernel_122267/3088769827.py:14: FutureWarning: The default value of regex will change from True to False in a future version.
  master.loc[master.endA.isna(), 'endA'] = master.loc[master.endA.isna(), 'sid'].str.replace('[0-9]+:', '')

### Add the original gene coordinates

In [42]:
print('### Add the original gene coordinates ')

### Add the original gene coordinates

In [43]:
#master.loc[~master.geneid.isna(), 'geneid'] = master.loc[~master.geneid.isna(), 'geneid']

# add back the original gene start and end
master = master.merge(orig_genes_df[['start', 'end', 'geneid', 'strand']],
                      on='geneid', how='left')

# convert the startB/endB position into startB/endB for the TSS
# if the gene is + then the startB is uses as the tss otherwise
# the endB is used as the tss
master.loc[(master.strand == '+'), 'endB'] = master.loc[(master.strand == '+'), 'start']
master.loc[(master.strand == '+'), 'startB'] = master.loc[(master.strand == '+'), 'start'] - 1

master.loc[(master.strand == '-'), 'endB'] = master.loc[(master.strand == '-'), 'end']
master.loc[(master.strand == '-'), 'startB'] = master.loc[(master.strand == '-'), 'end'] - 1

# convert the coordinates from floats to ints
master.startA = master.startA.astype(int)
master.startB = master.startB.astype(int)
master.endA = master.endA.astype(int)
master.endB = master.endB.astype(int)

master.rename(columns={'start': 'gene_start', 'end': 'gene_end', 'strand': 'gene_strand'}, inplace=True)

In [44]:
master

,chrA,startA,endA,chrB,startB,endB,name,score,strand1,strand2,sid,genename,geneid,rsid_x,chr,pos,ref,alt,variant,ma_samples,maf,eqtl_pval,eqtl_beta,eqtl_slop_se,ac,an,r2,median_tpm,rsid_y,dist,eqtl_fdr,is_eqtl_pair,gene_start,gene_end,gene_strand
0,chr9,3280000,5285000,chr9,3364791,3364792,rs10974435_AL354941.1,.,+,-,9:4283682,AL354941.1,ENSG00000215297,rs10974435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3364329,3364792,-
1,chr9,3280000,5285000,chr9,3526003,3526004,rs10974435_RFX3,.,+,-,9:4283682,RFX3,ENSG00000080298,rs10974435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3218297,3526004,-
2,chr9,3280000,5285000,chr9,3526722,3526723,rs10974435_RFX3-AS1,.,+,+,9:4283682,RFX3-AS1,ENSG00000232104,rs10974435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3526723,3691814,+
3,chr9,3280000,5285000,chr9,3647334,3647335,rs10974435_AL354977.2,.,+,+,9:4283682,AL354977.2,ENSG00000237359,rs10974435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3647335,3648338,+
4,chr9,3280000,5285000,chr9,3875583,3875584,rs10974435_AL137071.1,.,+,+,9:4283682,AL137071.1,ENSG00000236724,rs10974435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3875584,3878809,+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,chr9,3295000,5300000,chr9,5096665,5096666,rs10814917_MTCO1P11,.,+,+,9:4296430,MTCO1P11,ENSG00000224083,rs10814917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5096666,5098193,+
734,chr9,3295000,5300000,chr9,5193557,5193558,rs10814917_AL133547.1,.,+,-,9:4296430,AL133547.1,ENSG00000237553,rs10814917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5193339,5193558,-
735,chr9,3295000,5300000,chr9,4984389,4984390,rs10814917_JAK2,.,+,+,9:4296430,JAK2,ENSG00000096968,rs10814917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,4984390,5128183,+
736,chr9,3295000,5300000,chr9,5110912,5110913,rs10814917_TCF3P1,.,+,+,9:4296430,TCF3P1,ENSG00000236567,rs10814917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5110913,5112849,+
737,chr9,3295000,5300000,chr9,5113548,5113549,rs10814917_IGHEP2,.,+,+,9:4296430,IGHEP2,ENSG00000254017,rs10814917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5113549,5114804,+

### Add info about closests gene

In [45]:
print('### Add info about closests gene')

### Add info about closests gene

In [46]:
print("# #### Add info about closests gene")

# check for the closets gene
closets_check = [0] * master.shape[0]
for i, sr in master.iterrows():
    rs_gene = (sr.sid, sr.geneid)
    if rs_gene in closest_gene.index:
        closets_check[i] = 1
master['is_closest_gene'] = closets_check
print('Found {} closest genes.'.format(sum(master['is_closest_gene'])))

# #### Add info about closests gene
Found 18 closest genes.

### Add colocalization data

In [47]:
print('### Add colocalization data')

### Add colocalization data

In [48]:
# add colocalization data for SNP and is_coloc_snp columns
tmp_coloc = coloc_sig_full[['chr', 'pos',
 'ppH0',
 'ppH1',
 'ppH2',
 'ppH3',
 'ppH4',
 'rsid',
 'geneid',                       
 'ref',
 'alt',
 'AC',
 'AF',
 'AN',
 'gwas_slope',
 'gwas_slope_se',
 'gwas_pval']]
tmp_coloc['sid'] = tmp_coloc['chr'].str.replace('chr', '') + ':' +  tmp_coloc['pos'].astype(str) # NEW
master = master.merge(tmp_coloc, on=['sid', 'geneid'], how='left')

/mnt/BioHome/jreyna/tmp//ipykernel_122267/4159951681.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_coloc['sid'] = tmp_coloc['chr'].str.replace('chr', '') + ':' +  tmp_coloc['pos'].astype(str) # NEW

In [49]:
master

,chrA,startA,endA,chrB,startB,endB,name,score,strand1,strand2,sid,genename,geneid,rsid_x,chr_x,pos_x,ref_x,alt_x,variant,ma_samples,maf,eqtl_pval,eqtl_beta,eqtl_slop_se,ac,an,r2,median_tpm,rsid_y,dist,eqtl_fdr,is_eqtl_pair,gene_start,gene_end,gene_strand,is_closest_gene,chr_y,pos_y,ppH0,ppH1,ppH2,ppH3,ppH4,rsid,ref_y,alt_y,AC,AF,AN,gwas_slope,gwas_slope_se,gwas_pval
0,chr9,3280000,5285000,chr9,3364791,3364792,rs10974435_AL354941.1,.,+,-,9:4283682,AL354941.1,ENSG00000215297,rs10974435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3364329,3364792,-,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chr9,3280000,5285000,chr9,3526003,3526004,rs10974435_RFX3,.,+,-,9:4283682,RFX3,ENSG00000080298,rs10974435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3218297,3526004,-,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chr9,3280000,5285000,chr9,3526722,3526723,rs10974435_RFX3-AS1,.,+,+,9:4283682,RFX3-AS1,ENSG00000232104,rs10974435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3526723,3691814,+,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,chr9,3280000,5285000,chr9,3647334,3647335,rs10974435_AL354977.2,.,+,+,9:4283682,AL354977.2,ENSG00000237359,rs10974435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3647335,3648338,+,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,chr9,3280000,5285000,chr9,3875583,3875584,rs10974435_AL137071.1,.,+,+,9:4283682,AL137071.1,ENSG00000236724,rs10974435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3875584,3878809,+,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,chr9,3295000,5300000,chr9,5096665,5096666,rs10814917_MTCO1P11,.,+,+,9:4296430,MTCO1P11,ENSG00000224083,rs10814917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5096666,5098193,+,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
734,chr9,3295000,5300000,chr9,5193557,5193558,rs10814917_AL133547.1,.,+,-,9:4296430,AL133547.1,ENSG00000237553,rs10814917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5193339,5193558,-,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
735,chr9,3295000,5300000,chr9,4984389,4984390,rs10814917_JAK2,.,+,+,9:4296430,JAK2,ENSG00000096968,rs10814917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,4984390,5128183,+,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
736,chr9,3295000,5300000,chr9,5110912,5110913,rs10814917_TCF3P1,.,+,+,9:4296430,TCF3P1,ENSG00000236567,rs10814917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5110913,5112849,+,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
737,chr9,3295000,5300000,chr9,5113548,5113549,rs10814917_IGHEP2,.,+,+,9:4296430,IGHEP2,ENSG00000254017,rs10814917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5113549,5114804,+,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Add column to filter on coloc snp status

In [50]:
print('### Add column to filter on coloc snp status')

### Add column to filter on coloc snp status

In [51]:
master['is_coloc_pair'] = (~master['ppH4'].isna()).astype(int)

print('After left merging master with the colocalization table there are {} entries.'.format(master.shape[0]))
after_cnt = sum(master['is_coloc_pair'])
print('Checking if I have the correct number of colocalized SNPs: before {}; after {}.'.\
      format(coloc_sig_df.shape[0], after_cnt))

After left merging master with the colocalization table there are 738 entries.
Checking if I have the correct number of colocalized SNPs: before 18; after 18.

### Add loop data

In [52]:
print('# #### Add loop data')

# check for the loop gene
loop_check = [0] * master.shape[0]
for i, sr in master.iterrows():

    # check closest gene
    rs_gene = (sr.sid, sr.geneid)
    if rs_gene in fivekb_gloops_uniq:
        loop_check[i] = 1       

master['has_fithichip_loop'] = loop_check
print('There are {} SNP-Gene loops.'.format(sum(loop_check)))

# #### Add loop data
There are 252 SNP-Gene loops.

### Add coloc-snp boolean column

In [53]:
print('Add coloc-snp boolean column')

Add coloc-snp boolean column

In [54]:
master['has_colocSNP_anchor'] = master.sid.isin(colocSNP_anchors_set).astype(int)
print('There are {} coloc-SNP anchors.'.format(sum(master['has_colocSNP_anchor'])))

There are 738 coloc-SNP anchors.

### Add LD SNP boolean column

In [55]:
# add a True/False (1/0) column for the presence of a direct coloc snp (non-LD)
is_ld_snps = [x not in coloc_snps for x in master.sid]
master['is_ld_snp'] = [int(x) for x in is_ld_snps]

### Final ordering

In [56]:
# #### Do the final reordering and saving

# Include PC HiC data when it's available
final_cols = ['sid', 
    'rsid',
    'geneid',
    'genename',
    'chrA',
    'endA',
    'startB',
    'endB',
    'is_eqtl_pair',
    'is_coloc_pair',
    'is_closest_gene',
    'has_fithichip_loop',
    'has_colocSNP_anchor',
    'is_ld_snp', 
    'eqtl_pval', 
    'eqtl_beta', 
     #'eqtl_fdr',
    'dist',
    'ppH0',
    'ppH1',
    'ppH2',
    'ppH3',
    'ppH4',
    'gene_start',
    'gene_end',
    'ref_x', 
    'alt_x',
    'AC',
    'AF',
    'AN',
    'gwas_slope',
    'gwas_slope_se',
    'gwas_pval',
    'gene_start', 'gene_end', 'gene_strand']

master = master[final_cols]
master.rename(columns={'chrA':'chrom',
                       'endA': 'snp_pos',
                       'ref_x': 'ref',
                       'alt_x': 'alt',
                       'startB': 'tss_start',
                       'endB': 'tss_end',
                       'genename': 'gene_name',
                       'geneid': 'geneid',
                       'pp_H0_Coloc_Summary': 'ppH0',
                       'pp_H1_Coloc_Summary': 'ppH1',
                       'pp_H2_Coloc_Summary': 'ppH2',
                       'pp_H3_Coloc_Summary': 'ppH3',
                       'pp_H4_Coloc_Summary': 'ppH4',
                       'pvalue': 'eqtl_pval',
                       'beta': 'eqtl_beta',
                       'fdr': 'eqtl_fdr',
                       'gwas_pval_nominal': 'gwas_pval'}, inplace=True)

master.sort_values(['chrom', 'snp_pos', 'tss_start', 'rsid'], inplace=True)
master.snp_pos = master.snp_pos.astype(int)

# write out the master data
fn = os.path.join(outdir, 'master.tsv')
os.makedirs(outdir, exist_ok=True)
master.to_csv(fn, sep='\t', header=True, index=False)

#fn = os.path.join(outdir, 'master.xlsx')
#excel_master = master.sort_values('rsid').set_index('rsid')
#excel_master.to_excel(fn, na_rep='nan')

/mnt/BioHome/jreyna/tmp//ipykernel_122267/466200283.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master.rename(columns={'chrA':'chrom',
/mnt/BioHome/jreyna/tmp//ipykernel_122267/466200283.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master.sort_values(['chrom', 'snp_pos', 'tss_start', 'rsid'], inplace=True)
/mnt/BioHome/jreyna/tmp//ipykernel_122267/466200283.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master.snp_pos = master.snp_pos.astype(int)

In [58]:
fn

'results/main/sgls/ldpairs/T1D_34012112_Gaulton/GRCh37/Quach_2016/monocyte_R848/monocyte_naive/master.tsv'