In [29]:
import os 
import pandas as pd 
os.chdir("/mnt/BioHome/jreyna/jreyna/projects/dchallenge/")
import glob

In [30]:
# loading and concat all the data
data = []
for fn in glob.glob('results/main/loop_analysis/test/T1D_34012112_Gaulton/*/*/*/master.tsv'):
    
    dice_cline = fn.split('/')[4]
    study = fn.split('/')[5]
    eqtl_cline = fn.split('/')[6]
    
    df = pd.read_table(fn, header=0)
    df['dice_cline'] = dice_cline
    df['eqtl_cline'] = eqtl_cline
    df['study'] = study
    data.append(df)
    
data = pd.concat(data)
data.rename(columns={'5kb_gname': 'fivekb_gname'}, inplace=True)

In [31]:
data.columns.tolist()

['rs_id',
 'gene_name',
 'gene_id',
 'chrom',
 'snp_pos',
 'gene_start',
 'gene_end',
 'is_eqtl_pair',
 'is_coloc_pair',
 'is_closest_gene',
 'has_fithichip_loop',
 'sid',
 'nvar',
 'shape1',
 'shape2',
 'dist',
 'npval',
 'slope',
 'ppval',
 'bpval',
 'qval',
 'pp_H0_Coloc_Summary',
 'pp_H1_Coloc_Summary',
 'pp_H2_Coloc_Summary',
 'pp_H3_Coloc_Summary',
 'pp_H4_Coloc_Summary',
 'ref',
 'alt',
 'AC',
 'AF',
 'AN',
 'gwas_slope',
 'gwas_slope_se',
 'gwas_pval_nominal',
 'SampleSize',
 'dice_cline',
 'eqtl_cline',
 'study']

In [32]:
new_order = [
 'rs_id',
 'gene_name',
 'dice_cline',
 'eqtl_cline',
 'study',
 'gene_id',
 'chrom',
 'snp_pos',
 'gene_start',
 'gene_end',
 'is_eqtl_pair',
 'is_coloc_pair',
 'is_closest_gene',
 'has_fithichip_loop',
 'sid',
 'nvar',
 'shape1',
 'shape2',
 'dist',
 'npval',
 'slope',
 'ppval',
 'bpval',
 'qval',
 'pp_H0_Coloc_Summary',
 'pp_H1_Coloc_Summary',
 'pp_H2_Coloc_Summary',
 'pp_H3_Coloc_Summary',
 'pp_H4_Coloc_Summary',
 'ref',
 'alt',
 'AC',
 'AF',
 'AN',
 'gwas_slope',
 'gwas_slope_se',
 'gwas_pval_nominal',
 'SampleSize']

In [33]:
data

,rs_id,gene_name,gene_id,chrom,snp_pos,gene_start,gene_end,is_eqtl_pair,is_coloc_pair,is_closest_gene,...,AC,AF,AN,gwas_slope,gwas_slope_se,gwas_pval_nominal,SampleSize,dice_cline,eqtl_cline,study
0,rs1783521,MARK2,ENSG00000072518.16,chr11,64106291.0,63606400.0,63678491.0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,BLUEPRINT_eQTL,TH2
1,rs1783521,RNU6-1306P,ENSG00000202089.1,chr11,64106291.0,63650059.0,63650157.0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,BLUEPRINT_eQTL,TH2
2,rs1783521,RCOR2,ENSG00000167771.5,chr11,64106291.0,63678693.0,63684316.0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,BLUEPRINT_eQTL,TH2
3,rs1783521,NAA40,ENSG00000110583.8,chr11,64106291.0,63706431.0,63724800.0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,BLUEPRINT_eQTL,TH2
4,rs1783521,RNU6-45P,ENSG00000207200.1,chr11,64106291.0,63737942.0,63738048.0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,BLUEPRINT_eQTL,TH2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2563,NaN,FUT7,NaN,NaN,NaN,NaN,NaN,1,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,DICE_eQTL,CM
2564,NaN,RP11-229P13.15,NaN,NaN,NaN,NaN,NaN,1,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,DICE_eQTL,CM
2565,NaN,SAPCD2,NaN,NaN,NaN,NaN,NaN,1,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,DICE_eQTL,CM
2566,NaN,UAP1L1,NaN,NaN,NaN,NaN,NaN,1,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,DICE_eQTL,CM
2567,NaN,NOXA1,NaN,NaN,NaN,NaN,NaN,1,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,DICE_eQTL,CM

In [42]:
data[(data.is_eqtl_pair == 0) & (data.is_coloc_pair == 0) & (data.has_fithichip_loop == 1)]

,rs_id,gene_name,gene_id,chrom,snp_pos,gene_start,gene_end,is_eqtl_pair,is_coloc_pair,is_closest_gene,...,AC,AF,AN,gwas_slope,gwas_slope_se,gwas_pval_nominal,SampleSize,dice_cline,eqtl_cline,study
6,rs1783521,AP000721.4,ENSG00000256100.1,chr11,64106291.0,63742092.0,63755818.0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,BLUEPRINT_eQTL,TH2
7,rs1783521,OTUB1,ENSG00000167770.7,chr11,64106291.0,63753325.0,63769283.0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,BLUEPRINT_eQTL,TH2
13,rs1783521,STIP1,ENSG00000168439.12,chr11,64106291.0,63952744.0,63972015.0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,BLUEPRINT_eQTL,TH2
32,rs1783521,TRMT112,ENSG00000173113.2,chr11,64106291.0,64083932.0,64085556.0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,BLUEPRINT_eQTL,TH2
33,rs1783521,PRDX5,ENSG00000126432.9,chr11,64106291.0,64085560.0,64089283.0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,BLUEPRINT_eQTL,TH2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,rs12148472,RASGRF1,ENSG00000058335.11,chr15,79231478.0,79252289.0,79383115.0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,DICE_eQTL,CM
229,rs4788084,CLN3,ENSG00000261832.1,chr16,28539848.0,28477974.0,28503333.0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,DICE_eQTL,CM
230,rs4788084,CLN3,ENSG00000188603.12,chr16,28539848.0,28477983.0,28506896.0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,DICE_eQTL,CM
231,rs4788084,APOBR,ENSG00000184730.6,chr16,28539848.0,28505970.0,28510291.0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,DICE_eQTL,CM
233,rs4788084,NUPR1,ENSG00000176046.7,chr16,28539848.0,28548606.0,28550495.0,0,0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1D_34012112_Gaulton,DICE_eQTL,CM

In [20]:
data = data.loc[:, new_order]

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['is_eqtl_pair', 'dist'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

In [ ]:
master_fn = 'results/main/loop_analysis/super_master.snp_gene_loop.analysis.tsv'
data.to_csv(master_fn, sep='\t', index=False, na_rep='nan')

In [12]:
master_fn = 'results/main/loop_analysis/super_master.snp_gene_loop.analysis.xlsx'
xdata = data.sort_values(['rs_id', 'dice_cline', 'eqtl_cline', 'gene_name', 'study'])
xdata.set_index(['rs_id', 'dice_cline', 'eqtl_cline', 'gene_name', 'study']).to_excel(master_fn, na_rep='nan')